language: generic
sudo: required
services:
  -docker

before_install:
  -docker build -t nchetanad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nchetanad/docker-react npm run test